### ISSUE TITLE
感谢作者做出这么棒的作品, 有几点建议提一下。

### ISSUE THREAD

**Issue by songzhengpei** [msterzhang/onelist_app#1]
1.首先服务端做的很棒
2. 最主要的是移动端能够支持第三方播放。毕竟从零开始设计一款使用便捷，功能丰富的播放器还需要蛮久的。因此将onelist移动端做影视库整理和海报墙。通过kodi播放应该体验刚好。
3. 希望作者在服务端能够给出刮削的影视命名规则。这边影视剧集还是刮削成功率低了一，暂时暂时还没有研究出命名规则是什么样的。
4. 希望作者加油！哪里有充电激励的地方？以表支持。

**Comment by msterzhang** [comment]
已在研究如何调用kodi播放，命名规则：
挂载的目录中文件必须满足下面这种命名方式

电影就按电影名称

电视同一部美剧，所有季可以分开或者放在不同子目录，但是文件名一定得满足以下格式
权力的游戏S01E01.mp4
权力的游戏S01E02.mp4
权力的游戏S01E03.mp4

非常感谢支持，如想支持作者开发，可看服务端说明文件
