### ISSUE TITLE
视频无法播放，提示播放异常

### ISSUE THREAD

**Issue by dudukee** [msterzhang/onelist_app#2]
手机端运行

Alist 版本 3.31.0
OneList版本 2.0.5
app版本 1.0.3

播放阿里云盘资源时报错：播放异常，重试
日志：
I/flutter (31128): [war] 2024-03-06 17:13:30.905383 [fplayer] call setDataSource with both autoPlay and showCover true, showCover will be ignored
I/flutter (31128): [inf] 2024-03-06 17:13:30.905578 [fplayer] FPlayer{id:2} invoke setDataSource **[隐藏域名信息]**/d/alist/汪汪队1-8季全国语配音/第1季1080P/汪汪队立大功-S01E01.mp4
D/IJKMEDIA(31128): IjkMediaPlayer_setDataSourceAndHeaders
V/IJKMEDIA(31128): setDataSource: path **[隐藏域名信息]**/d/alist/汪汪队1-8季全国语配音/第1季1080P/汪汪队立大功-S01E01.mp4
D/IJKMEDIA(31128): ijkmp_set_data_source(url="**[隐藏域名信息]**/d/alist/汪汪队1-8季全国语配音/第1季1080P/汪汪队立大功-S01E01.mp4")
D/IJKMEDIA(31128): ijkmp_set_data_source(url="**[隐藏域名信息]**/d/alist/汪汪队1-8季全国语配音/第1季1080P/汪汪队立大功-S01E01.mp4")=0
I/flutter (31128): [inf] 2024-03-06 17:13:30.907662 [fplayer] FPlayer{id:2} state changed to FState.initialized <= FState.idle
I/flutter (31128): [inf] 2024-03-06 17:13:30.910101 [fplayer] FPlayer{id:2} setOption k:headers, v:
I/flutter (31128): [inf] 2024-03-06 17:13:30.910515 [fplayer] FPlayer{id:2} invoke prepareAsync and start #1
I/flutter (31128): [inf] 2024-03-06 17:13:30.910616 [fplayer] FPlayer{id:2} setOption k:start-on-prepared, v:1
D/IJKMEDIA(31128): IjkMediaPlayer_setOption
D/IJKMEDIA(31128): IjkMediaPlayer_setOptionLong
D/IJKMEDIA(31128): IjkMediaPlayer_setOption
D/IJKMEDIA(31128): IjkMediaPlayer_prepareAsync
D/IJKMEDIA(31128): ijkmp_prepare_async()
I/IJKMEDIA(31128): ===== versions =====
I/IJKMEDIA(31128): ijkplayer    : 
I/IJKMEDIA(31128): FFmpeg       : ff4.0-20230611
I/IJKMEDIA(31128): libavutil    : 56.14.100
I/IJKMEDIA(31128): libavcodec   : 58.18.100
I/IJKMEDIA(31128): libavformat  : 58.12.100
I/IJKMEDIA(31128): libswscale   : 5.1.100
I/IJKMEDIA(31128): libswresample: 3.1.100
I/IJKMEDIA(31128): ===== options =====
I/IJKMEDIA(31128): player-opts : enable-position-notify       = 1
I/IJKMEDIA(31128): player-opts : soundtouch                   = 1
I/IJKMEDIA(31128): player-opts : reconnect                    = 20
I/IJKMEDIA(31128): player-opts : framedrop                    = 20
I/IJKMEDIA(31128): player-opts : enable-accurate-seek         = 1
I/IJKMEDIA(31128): player-opts : mediacodec                   = 1
I/IJKMEDIA(31128): player-opts : packet-buffering             = 0
I/IJKMEDIA(31128): player-opts : start-on-prepared            = 1
I/IJKMEDIA(31128): player-opts : overlay-format               = fcc-_es2
I/IJKMEDIA(31128): format-opts : ijkapplication               = -5476376616797327312
I/IJKMEDIA(31128): format-opts : ijkiomanager                 = -5476376616835627392
I/IJKMEDIA(31128): format-opts : headers                      = 
I/IJKMEDIA(31128): ===================
I/IJKMEDIA(31128): SDL_RunThread: [31306] ff_msg_loop
D/IJKMEDIA(31128): message_loop
D/IJKMEDIA(31128): FFP_MSG_FLUSH:
D/IJKMEDIA(31128): ijkmp_prepare_async()=0
I/flutter (31128): [inf] 2024-03-06 17:13:30.914002 [fplayer] FPlayer{id:2} state changed to FState.asyncPreparing <= FState.initialized
I/flutter (31128): [inf] 2024-03-06 17:13:30.914297 [fplayer] FPlayer{id:2} invoke prepareAsync and start #1 -> done
I/flutter (31128): [inf] 2024-03-06 17:13:30.914483 [fplayer] FPlayer{id:2} state changed to FState.initialized <= FState.idle
I/flutter (31128): [inf] 2024-03-06 17:13:30.914717 [fplayer] FPlayer{id:2} state changed to FState.asyncPreparing <= FState.initialized
I/IJKMEDIA(31128): SDL_RunThread: [31308] ff_read
W/IJKMEDIA(31128): No trailing CRLF found in HTTP header.
I/IJKMEDIA(31128): SDL_RunThread: [31307] ff_vout
I/IJKMEDIA(31128): cur ipv4 c_ipaddr = 152.69.199.252
I/IJKMEDIA(31128): tcp did open uri = tcp://**[隐藏域名信息]**:443, ip =  port = 0
I/IJKMEDIA(31128): request: GET /d/alist/汪汪队1-8季全国语配音/第1季1080P/汪汪队立大功-S01E01.mp4 HTTP/1.1
I/IJKMEDIA(31128): User-Agent: Lavf/58.12.100
I/IJKMEDIA(31128): Accept: */*
I/IJKMEDIA(31128): Range: bytes=0-
I/IJKMEDIA(31128): Connection: close
I/IJKMEDIA(31128): Host: **[隐藏域名信息]**
I/IJKMEDIA(31128): Icy-MetaData: 1
I/IJKMEDIA(31128): 
I/IJKMEDIA(31128): 
I/IJKMEDIA(31128): 
I/IJKMEDIA(31128): header='HTTP/1.1 200 OK'
I/IJKMEDIA(31128): header='Server: nginx'
I/IJKMEDIA(31128): header='Date: Wed, 06 Mar 2024 09:13:31 GMT'
I/IJKMEDIA(31128): header='Content-Type: application/json; charset=utf-8'
I/IJKMEDIA(31128): header='Content-Length: 51'
I/IJKMEDIA(31128): header='Connection: close'
I/IJKMEDIA(31128): header='Cache-Control: no-cache'
I/IJKMEDIA(31128): header=''
W/IJKMEDIA(31128): Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
E/IJKMEDIA(31128): moov atom not found
E/IJKMEDIA(31128): **[隐藏域名信息]**/d/alist/汪汪队1-8季全国语配音/第1季1080P/汪汪队立大功-S01E01.mp4: Invalid data found when processing input
I/IJKMEDIA(31128): SDL_JNI_DetachThreadEnv: [31308]
D/IJKMEDIA(31128): FFP_MSG_ERROR: -1094995529
E/tv.danmaku.ijk.media.player.IjkMediaPlayer(31128): Error (-1094995529,0,Invalid data found when processing input)

**Comment by msterzhang** [comment]
[隐藏域名信息]/d/alist/汪汪队1-8季全国语配音/第1季1080P/汪汪队立大功-S01E01.mp4 这个链接能下载访问吗？有没有关闭alist的签名所有

**Comment by dudukee** [comment]
关闭alist的签名所有后，可以正常播放，感谢回复
